### ISSUE TITLE
Incomplete type declaration file

### ISSUE THREAD

**Issue by soumyamishra89** [react-native-community/progress-bar-android#36]
# Bug

1. The index.d.ts file is missing the VIewProps that the progressbar inherits from.
2. Also the example in the REDAME file says 
`import { ProgressBar } from '@react-native-community/progress-bar-android';`
but there is no ProgressBar declared. it is ProgressBarAndroid.

**Comment by Naturalclar** [comment]
@soumyamishra89 Thanks for the issue! Released v1.0.2 with fixes included :tada:
