### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCProgressBar" was not found in the UIManager

### ISSUE THREAD

**Issue by RKuerten** [react-native-community/progress-bar-android#41]
# Bug
Can't use the component at all, this error always happens. I'm using the component in my app as it follows:

```
<ProgressBar
    color={Colors.visitedMarker} //#70B108
    progress={getVisited(user, route) / route.stops.length} //Always between 0 and 1
    style={styles.progressBar}
    styleAttr="Horizontal"
/>
```
![photo_2020-04-28_18-35-56](https://user-images.githubusercontent.com/30464993/80540199-38803680-897f-11ea-8965-113930ee64c9.jpg)

## Environment info
```
"expo": "^36.0.0",
"react": "16.9.0",
"react-dom": "16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
```

Library version: 1.0.2
Testing it on a Redmi 4x, Android 7.1.2

## Steps To Reproduce

1. Simply add the library to your app dependencies, using either npm, yarn, or expo itself.
2. Add one of the examples from the README.md into your code

Describe what you expected to happen:

1. I expected it to work...

## Reproducible sample code
This snack below is merely a reproduction of the code from the README + the snippet I tried to use within my app. It doesn't work, giving a somewhat similar (but not the same) error.

https://snack.expo.io/@r_kuerten/668748

**Comment by Naturalclar** [comment]
@RKuerten This module is not supported for Expo SDK 36 or below, since this modules requires installing native component.
However, expo sdk 36 still provides ProgressBarAndroid component in the `react-native` package.

Either upgrade your sdk to 37, or use `import {ProgressBarAndroid} from 'react-native'`

Thanks 😄

**Comment by Relax594** [comment]
@Naturalclar i get the same issue and im not using expo.

**Comment by bernardnongpoh** [comment]
@Relax594  I am facing the same issue with RN 0.62.2. Did you find any solution?

**Comment by bernardnongpoh** [comment]
I found the solution. We need to manually link the library  (I am using RN0.62.2) Still linking not done manually
Following are the steps 
1. `npm install @react-native-community/progress-bar-android --save`
2.  `react-native link @react-native-community/progress-bar-android`
3.  Open up `android/app/src/main/java/[...]/MainActivity.java`
4. Add `import com.reactnativecommunity.androidprogressbar.RNCProgressBarPackage;` to the imports at the top of the file
5. Add `new RNCProgressBarPackage()` to the list returned by the `getPackages()` method
6. Append the following lines to android/settings.gradle:
```
include ':@react-native-community_progress-bar-android'
project(':@react-native-community_progress-bar-android').projectDir = new File(rootProject.projectDir, 	'../../node_modules/@react-native-community/progress-bar-android/android')
```
7. Insert the following lines inside the dependencies block in android/app/build.gradle:
`implementation project(':@react-native-community_progress-bar-android')`

**Comment by Ryuta1346** [comment]
@Naturalclar
I am facing the same issue with expo37 using managed flow.
Is this module not supported for managed flow?

**Comment by sameerahmed56** [comment]
I found the solution while trying. 
uninstall the last library that you had installed in my case it was 
1. npm uninstall react-native-pdf
2. npm install react-native-pdf
3. npm install @react-native-community/progress-bar-android 
4. cd android && gradlew clean
5. cd.. && react-native run-android
it solved my problem.

**Comment by iamrameshwar** [comment]
"@react-native-community/progress-view": "^1.2.3", use this version paste this in package.json and delete nodemodule and reinstall
