### ISSUE TITLE
Where to add Windows implementation?

### ISSUE THREAD

**Issue by kaiguo** [react-native-community/progress-bar-android#45]
# Question

Hi @Naturalclar, we are thinking of adding Windows support and noticed there are two separate repos, progress-bar-android for Android and [progress-view](https://github.com/react-native-community/progress-view) for iOS, any guidance on which repo we should add Windows implementation to?

**Comment by kaiguo** [comment]
@TatianaKapos FYI.

**Comment by Naturalclar** [comment]
@kaiguo I'm thinking of merging progressbar-android and progressview into the progressview repository, since that way it won't require any renaming.

**Comment by kaiguo** [comment]
OK, sounds good, we'll add it to progressview repo then, thanks!
